# Site settings
title: Logan Arnett
email: logan@loganarnett.com
description: "The Blog of Logan Arnett about his journey into the world of Web Development from his time as a student at The Iron Yard through his career beyond."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Logan_Arnett
  - title: facebook
    url: https://www.facebook.com/logan.arnett
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/LoganArnett

# Postal address (add as many lines as necessary)
address:
  - line: Winter Garden and Orlando FL Area

# Build settings
markdown: kramdown
permalink: pretty
