# Site settings
title: Rx Web Development
email: logan@loganarnett.com
description: "Web Development that is prescribed to you, your company, and optimized for your industry. Rx Web Development cures your web page and website issues by developing beautiful and interactive designs to draw in your end users and target market. Most of all the ease of use will keep them there. Rx Web Development: Websites as Prescribed."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Logan_Arnett
  - title: facebook
    url: https://www.facebook.com/logan.arnett
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/LoganArnett

# Postal address (add as many lines as necessary)
address:
  - line: Winter Garden and Orlando FL Area

# Build settings
markdown: kramdown
permalink: pretty
